const { Schema, model } = require("mongoose");

const productSchema = new Schema(
  {
    name: { type: String, required: [true, "name is required"] },
    description: String,
    price: { type: Number, Required: [true, "price is required"], min: 0 },
    category: {
      type: String,
      enum: [
        "Food & Beverages",
        "Regional Delicacies",
        "Austrian Wines",
        "Beer & Craft Beverages",
        "Organic & Sustainable Foods",
        "Clothing & Traditional Wear",
        "Dirndl & Lederhosen",
        "Traditional Accessories",
        "Modern Fashion",
        "Outdoor & Alpine Clothing",
        "Home & Living",
        "Austrian Pottery & Ceramics",
        "Handmade Linens & Textiles",
        "Alpine-Style Home Décor",
        "Furniture",
        "Arts & Crafts",
        "Austrian Paintings & Sculptures",
        "Woodwork & Handcrafted Items",
        "Traditional Folk Art",
        "Jewelry",
        "Books & Media",
        "Austrian Literature & History Books",
        "Travel Guides for Austria",
        "Music",
        "Films & Documentaries",
        "Health & Beauty",
        "Natural Skincare",
        "Wellness & Spa Products",
        "Austrian Health Supplements",
        "Essential Oils",
        "Sports & Outdoors",
        "Ski Equipment & Gear",
        "Hiking Accessories",
        "Cycling Equipment",
        "Fitness Wear",
        "Toys & Hobbies",
        "Traditional Wooden Toys",
        "Board Games",
        "Hobby Kits",
        "Musical Instruments",
        "Local Products",
        "Austrian Souvenirs",
        "Handmade Crafts from Local Artisans",
        "Specialty Cheeses & Meats",
        "Eco-Friendly & Sustainable Products",
        "Seasonal Categories",
        "Christmas Market Goods",
        "Advent Wreaths & Calendars",
        "Ornaments & Decorations",
        "Glühwein Sets",
      ],
      required: [true, "category is required"],
    },
    image: String,
    stock: { type: Number, min: [0, "Has to be over 0"] },
    owner: {
      type: Schema.Types.ObjectId,
      ref: "User",
      required: [true, "owner is required"],
    },
  },
  {
    timestamps: true, // add creation time and update time automaticlly
  }
);
const Product = model("Product", productSchema);
module.exports = Product;
